/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sistema_asignacion.Fronted.UI;

import com.mycompany.sistema_asignacion.Backen.Exceptions.CloneNodeException;
import com.mycompany.sistema_asignacion.Backen.Exceptions.InvalidStructureException;
import com.mycompany.sistema_asignacion.Backen.Objetos.DatosSistema;
import com.mycompany.sistema_asignacion.Backen.Objetos.Edificio;
import com.mycompany.sistema_asignacion.Backen.Objetos.Salon;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author benjamin
 */
public class CrearSalon extends javax.swing.JInternalFrame {

    private DatosSistema datosSistema;

    /**
     * Creates new form CrearSalon
     */
    public CrearSalon(DatosSistema datosSistema) {
        this.datosSistema = datosSistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FieldNumSalon = new javax.swing.JFormattedTextField();
        FieldCapacidad = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        FieldEdificio = new javax.swing.JTextField();
        ButtonCrear = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("CREAR SALON");

        jLabel1.setText("Numero de Salon:");

        jLabel2.setText("Capacidad:");

        FieldNumSalon.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FieldNumSalon.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        FieldCapacidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FieldCapacidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Edificio");

        ButtonCrear.setText("Crear");
        ButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FieldCapacidad)
                            .addComponent(FieldNumSalon)
                            .addComponent(FieldEdificio, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(ButtonCrear)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FieldEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FieldNumSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FieldCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonCrear)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCrearActionPerformed
        // TODO add your handling code here:
        String edificio = this.FieldEdificio.getText();
        Edificio edificio1 = datosSistema.getEdificios().buscar(edificio);

        if (edificio1 != null) {
            if (comprobarNumero(this.FieldCapacidad.getText())) {
                int capacidad = Integer.valueOf(this.FieldCapacidad.getText());
                if (comprobarNumero(this.FieldNumSalon.getText())) {
                    int numeroSalon = Integer.valueOf(this.FieldNumSalon.getText());
                    try {
                        Salon newSalon = new Salon(numeroSalon, capacidad, edificio);
                        edificio1.getSalones().agregarOrden(newSalon, String.valueOf(newSalon.getNumeroSalon()));
                        JOptionPane.showMessageDialog(this, "El salon \""+numeroSalon+"\" se registro conrrectamente en el edificio", "Completado", JOptionPane.INFORMATION_MESSAGE);
                        
                        this.FieldCapacidad.setText(null);
                        this.FieldEdificio.setText(null);
                        this.FieldNumSalon.setText(null);
                        
                    } catch (CloneNodeException ex) {
                        JOptionPane.showMessageDialog(this, "Ya existe un salon \""+numeroSalon+"\" en el edificio", "Error de Registro", JOptionPane.WARNING_MESSAGE);
                    } catch (InvalidStructureException ex) {
                        JOptionPane.showMessageDialog(this, "No se puede guardar el salon:\n"+ex.getMessage(), "Error de Registro", JOptionPane.WARNING_MESSAGE);
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Numerod e salon no valido debe contener caracteres numericos", "Error de Registro", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Capacidad no valida debe contener caracteres numericos", "Error de Registro", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe un edificio \""+edificio+"\" en el sistema", "Error de Busqueda", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ButtonCrearActionPerformed

    private boolean comprobarAlfanumerico(String cadena) {
        return Pattern.matches("^[0-9a-zA-ZÀ-ÿ\u00f1\u00d1]+$", cadena);
    }

    private boolean comprobarNumero(String cadena) {
        return Pattern.matches("^[0-9]+$", cadena);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCrear;
    private javax.swing.JFormattedTextField FieldCapacidad;
    private javax.swing.JTextField FieldEdificio;
    private javax.swing.JFormattedTextField FieldNumSalon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
