/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sistema_asignacion.Fronted.UI;

import com.mycompany.sistema_asignacion.Backen.Exceptions.CloneNodeException;
import com.mycompany.sistema_asignacion.Backen.Objetos.DatosSistema;
import com.mycompany.sistema_asignacion.Backen.Objetos.Estudiante;
import com.mycompany.sistema_asignacion.Backen.Objetos.Usuario;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author benjamin
 */
public class FrameCrearUsuario extends javax.swing.JInternalFrame {

    private DatosSistema dataSistema;

    /**
     * Creates new form FrameCrearUsuario
     */
    public FrameCrearUsuario(DatosSistema datosSistema) {
        this.dataSistema = datosSistema;
        initComponents();
        this.idAutomatico();
    }
    
    private void idAutomatico(){
        try {
            this.FieldId.setText(String.valueOf(this.dataSistema.getUsuarios().getUltimo().getId()+1));
        } catch (Exception e) {
            /**Do noting error despreciable*/
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FieldUser = new javax.swing.JTextField();
        FieldPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        tipoUser = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        FieldId = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("CREAR USUARIO");

        jLabel1.setText("Usuario:");

        jLabel2.setText("Password:");

        FieldUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        FieldPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FieldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldPassActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo:");

        tipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "colaborador", "estudiante", "super" }));

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Id:");

        FieldId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FieldId.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FieldPass, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(tipoUser, 0, 127, Short.MAX_VALUE)
                    .addComponent(FieldUser, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(FieldId))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(FieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(FieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user = this.FieldUser.getText();
        if (user.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe de escribir un usuario", "Error de registro", JOptionPane.WARNING_MESSAGE);
        } else {
            String pass1 = String.valueOf(this.FieldPass.getPassword());
            if (this.comprobarAlfanumerico(user)) {
                if (pass1.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe de escribir y confirmar la contraseña", "Error de registro", JOptionPane.WARNING_MESSAGE);
                } else {

                    int identificador = Integer.valueOf(this.FieldId.getText());

                    if (this.dataSistema.getUsuarios().buscar(new Usuario(identificador, "", "", "")) == null) {
                        if (comprobarAlfanumerico(pass1)) {
                            try {
                                String tipo = this.tipoUser.getItemAt(this.tipoUser.getSelectedIndex());
                                Usuario newUser = new Usuario(identificador, user, pass1, tipo);
                                
                                if(tipo.equals("estudiante")){
                                    Estudiante tmp = new Estudiante(identificador,"","");
                                    if(this.dataSistema.getEstudiantes().buscar(tmp, tmp.hashCode())!=null){
                                        this.dataSistema.getUsuarios().add(newUser, newUser.getNombre());
                                        JOptionPane.showMessageDialog(this, "Se creo con exito el usuario \"" + user + "\" en el sistema", "Registro Completado", JOptionPane.INFORMATION_MESSAGE);
                                        this.FieldUser.setText(null);
                                        this.FieldPass.setText(null);
                                        this.tipoUser.setSelectedIndex(0);
                                        this.idAutomatico();
                                    }else{
                                        JOptionPane.showMessageDialog(this, "No hay referencia del estudiante \"" + identificador + "\" en el sistema", "Error de registro", JOptionPane.WARNING_MESSAGE);
                                    }
                                }else{
                                    this.dataSistema.getUsuarios().add(newUser, newUser.getNombre());
                                    JOptionPane.showMessageDialog(this, "Se creo con exito el usuario \"" + user + "\" en el sistema", "Registro Completado", JOptionPane.INFORMATION_MESSAGE);
                                    this.FieldUser.setText(null);
                                    this.FieldPass.setText(null);
                                    this.tipoUser.setSelectedIndex(0);
                                    this.idAutomatico();
                                }
                            } catch (CloneNodeException e) {
                                JOptionPane.showMessageDialog(this, "Ya existe un usuario \"" + user + "\" en el sistema", "Error de registro", JOptionPane.WARNING_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "La contraseña debe contener caracteres alfanumericos", "Error de registro", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Ya existe un usuario con identidicador \""+identificador+"\"", "Error de registro", JOptionPane.WARNING_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "El usuario debe contener caracteres alfanumericos", "Error de registro", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private boolean comprobarAlfanumerico(String cadena) {
        return Pattern.matches("^[0-9a-zA-ZÀ-ÿ\u00f1\u00d1]+$", cadena);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FieldId;
    private javax.swing.JPasswordField FieldPass;
    private javax.swing.JTextField FieldUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> tipoUser;
    // End of variables declaration//GEN-END:variables
}
