/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sistema_asignacion.Fronted.UI.Estudiantes;

import com.mycompany.sistema_asignacion.Backen.Objetos.DatosSistema;
import com.mycompany.sistema_asignacion.Backen.Objetos.Estudiante;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Elenita
 */
public class ModificarEstudiante extends javax.swing.JInternalFrame {
    
    private DatosSistema datosSistema;
    /**
     * Creates new form ModificarEstudiante
     */
    public ModificarEstudiante(DatosSistema datosSistema) {
        this.datosSistema=datosSistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FieldBuscarCarnet = new javax.swing.JFormattedTextField();
        ButtonBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FieldCarnte = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FiledNombre = new javax.swing.JTextField();
        FieldDireccion = new javax.swing.JTextField();
        ButtonModificar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("MODIFICAR ESTUDIANTE");
        setToolTipText("");

        jLabel1.setText("Numero de Carnet:");

        FieldBuscarCarnet.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#########"))));
        FieldBuscarCarnet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FieldBuscarCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldBuscarCarnetActionPerformed(evt);
            }
        });

        ButtonBuscar.setText("Buscar");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Carnet:");

        FieldCarnte.setEditable(false);

        jLabel3.setText("Nombre:");

        jLabel4.setText("Direccion:");

        FiledNombre.setEditable(false);

        FieldDireccion.setEditable(false);

        ButtonModificar.setText("Modificar");
        ButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FiledNombre)
                            .addComponent(FieldDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addComponent(ButtonModificar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(FieldCarnte, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FieldCarnte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FiledNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonModificar))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(FieldBuscarCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonBuscar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldBuscarCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBuscar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean comprobarAlfanumerico(String cadena) {
        return Pattern.matches("^[0-9a-zA-ZÀ-ÿ\u00f1\u00d1]+[ 0-9a-zA-ZÀ-ÿ\u00f1\u00d1]*$", cadena);
    }
    
    private void FieldBuscarCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldBuscarCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldBuscarCarnetActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        // TODO add your handling code here:
        int numeroCarnet = Integer.valueOf(this.FieldBuscarCarnet.getText());
        Estudiante newEstudiante = new Estudiante(numeroCarnet, "", "");
        Estudiante tmp = datosSistema.getEstudiantes().buscar(newEstudiante, newEstudiante.hashCode());
        if(tmp!=null){
            this.FieldCarnte.setText(String.valueOf(tmp.getCarnet()));
            this.FiledNombre.setText(tmp.getNombre());
            this.FieldDireccion.setText(tmp.getDireccion());
            this.FiledNombre.setEditable(true);
            this.FieldDireccion.setEditable(true);
            this.ButtonModificar.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(this, "No existe un estudiante con el numero de carnet \""+newEstudiante.getCarnet()+"\"","Error de busqueda", JOptionPane.WARNING_MESSAGE);
            this.FieldCarnte.setText(null);
            this.FiledNombre.setText(null);
            this.FieldDireccion.setText(null);
            this.FiledNombre.setEditable(false);
            this.FieldDireccion.setEditable(false);
            this.ButtonModificar.setEnabled(false);
        }
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarActionPerformed
        // TODO add your handling code here:
        int numeroCarnet = Integer.valueOf(this.FieldCarnte.getText());
        
        String nombre = this.FiledNombre.getText();
        String direccion = this.FieldDireccion.getText();
        
        Estudiante newEstudiante = new Estudiante(numeroCarnet, "", "");
        Estudiante tmp = datosSistema.getEstudiantes().buscar(newEstudiante, newEstudiante.hashCode());
        
        if(tmp!=null){
            if(comprobarAlfanumerico(nombre)){
                if(comprobarAlfanumerico(direccion)){
                    tmp.setNombre(nombre);
                    tmp.setDireccion(direccion);
                    JOptionPane.showMessageDialog(this, "Estudiante modficado con exito","Modificacion", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "La direccion debe contener caracteres Alfanumericos","Error de modificacion", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "El nombre debe contener caracteres Alfanumericos","Error de modificacion", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "No existe un estudiante con el numero de carnet \""+newEstudiante.getCarnet()+"\"","Error de modificacion", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ButtonModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonModificar;
    private javax.swing.JFormattedTextField FieldBuscarCarnet;
    private javax.swing.JTextField FieldCarnte;
    private javax.swing.JTextField FieldDireccion;
    private javax.swing.JTextField FiledNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
