
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.mycompany.sistema_asignacion.Backen.Analizadores.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CATE = 4;
  public static final int SALON = 6;
  public static final int P_C = 16;
  public static final int TIPO_USER = 10;
  public static final int P_A = 15;
  public static final int HORARIO = 8;
  public static final int EDIF = 5;
  public static final int USER = 2;
  public static final int CADENA_DIA = 20;
  public static final int COMA = 17;
  public static final int STRING = 13;
  public static final int EOF = 0;
  public static final int DOT_COMA = 18;
  public static final int NUMERO = 19;
  public static final int ALFANUMERICO = 11;
  public static final int error = 1;
  public static final int CARNET = 12;
  public static final int STRING_SPACE = 14;
  public static final int ASIG = 9;
  public static final int CURSO = 7;
  public static final int CADENA_HORARIO = 21;
  public static final int ESTU = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "USER",
  "ESTU",
  "CATE",
  "EDIF",
  "SALON",
  "CURSO",
  "HORARIO",
  "ASIG",
  "TIPO_USER",
  "ALFANUMERICO",
  "CARNET",
  "STRING",
  "STRING_SPACE",
  "P_A",
  "P_C",
  "COMA",
  "DOT_COMA",
  "NUMERO",
  "CADENA_DIA",
  "CADENA_HORARIO"
  };
}

